# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "usb_storage" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # 8fd91622-84c1-428d-93c5-e94bf27a859b
  fileSystems."/" =
    { device = "/dev/mapper/nixos-root";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8698-1702";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # aef40e34-ede5-4f0b-97db-f019c6a7c94e
  swapDevices =
    [ { device = "/dev/mapper/nixos-swap"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}