# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "none";
      fsType = "tmpfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8EC3-37E1";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/nix" =
    { device = "cadance/private/nix";
      fsType = "zfs";
    };

  fileSystems."/media/scratch" =
    { device = "scratch/private";
      fsType = "zfs";
    };

  fileSystems."/media/Collection1" =
    { device = "candystor/collection1";
      fsType = "zfs";
    };

  fileSystems."/media/infowars" =
    { device = "candystor/infowars";
      fsType = "zfs";
    };

  fileSystems."/data" =
    { device = "cadance/private/persist";
      fsType = "zfs";
    };

  fileSystems."/storage" =
    { device = "candystor/storage";
      fsType = "zfs";
    };

  fileSystems."/downloads" =
    { device = "candystor/downloads";
      fsType = "zfs";
    };

  fileSystems."/media/video" =
    { device = "video";
      fsType = "zfs";
    };

  fileSystems."/storage/SyncRoot/Music" =
    { device = "candystor/music";
      fsType = "zfs";
    };

  fileSystems."/var/lib/immich" =
    { device = "cadance/private/immich";
      fsType = "zfs";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
