#!/usr/bin/env bash

function applyFiles () {
    local flag=$1; shift
    for i in "$@"; do
        [[ ( -d "$i" ) || ( -f "$i" ) || ( -S "$i" ) ]] && command+=("${flag}" "$i" "$i")
    done
}

command=(
    bwrap
    --setenv    OPENCODE_DISABLE_LSP_DOWNLOAD   true
    --setenv    OPENCODE_EXPERIMENTAL_LSP_TOOL  true
    --proc      /proc
    --die-with-parent
    --unshare-pid

    --ro-bind   /bin/sh      /bin/sh
    --ro-bind   /usr/bin/env /usr/bin/env
    --dev /dev
)

applyFiles --dev-bind /dev/dri /dev/dri

applyFiles --ro-bind        \
    /nix                    \
    /run/current-system     \
    /run/opengl-driver      \
    /etc                    \
    /sys/dev/char           \
    /sys/devices/pci0000:00 \
    /sys/devices/virtual

command+=(
    --tmpfs     /tmp
    --tmpfs     /home
)

applyFiles --ro-bind \
    "$HOME/.config/sops-nix/secrets/deepseek_api_key" \
    "$HOME/.config/sops-nix/secrets/agents/forgejo_token"

applyFiles --ro-bind    \
    "$HOME/.config/git" \
    "$HOME/.config/Croc"

applyFiles --bind                   \
    "$HOME/.pi"                     \
    "$HOME/.config/opencode"        \
    "$HOME/.local/share/opencode"   \
    "$HOME/.local/state/opencode"   \
    "$HOME/.local/share/cartopy"    \
    "/games"                        \
    "$HOME/Games"                   \
    "$HOME/Documents/Coding"        \
    /run/postgresql                 \
    /run/nscd                       \
    "$XDG_RUNTIME_DIR/wayland-0"    \
    "$XDG_RUNTIME_DIR/pipewire-0"   \

command+=(
    --symlink /run /var/run
)

applyFiles --bind "$PWD"

command+=(
    --chdir     "$PWD"
    --
)

command+=("$@")

exec "${command[@]}"
